main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/',views.about, name='about'),
    path('nfts/',views.nfts_index,name='index'),
    path('nfts/<int:nft_id>/',views.nfts_detail,name='detail'),

    #Create
    path('nfts/create',views.NftCreate.as_view(),name='nfts_create'),

    #Update
    path('nfts/<int:pk>/update/',views.NftUpdate.as_view(),name='nfts_update'),

    #Delete
    path('nfts/<int:pk>/delete/',views.NftDelete.as_view(),name='nfts_delete'),
    path('nfts/<int:nft_id>/add_selling/', views.add_selling, name='add_selling'),
]

nftcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from xmlrpc.client import boolean
from django.db import models
from django.urls import reverse

SELL = (
    ('S', 'Selling'),
    ('S', 'Sold')
)

# Create your models here.
class Nft(models.Model):
    token = models.CharField(max_length=100)
    creator = models.CharField(max_length=100)
    blockchain = models.CharField(max_length=100)
    owner = models.CharField(max_length=100, default = ' ')

    def __str__(self):
        return self.token

    def get_absolute_url(self):
        return reverse('detail', kwargs = {'nft_id': self.id})

class Selling(models.Model):
    date = models.DateField('Selling/Sold Date')
    sell = models.CharField(
        max_length=1,
        choices=SELL,
        default=SELL[0][0]
    )

    nft = models.ForeignKey(Nft, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_sell_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Selling

class SellingForm(ModelForm):
    class Meta:
        model = Selling
        fields = ['date', 'sell']

main_app/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Nft
from .forms import SellingForm
# Define the home view

def home(request):
  return HttpResponse('<h1>Hello /ᐠ｡‸｡ᐟ\ﾉ</h1>')
def about(request):
  return render(request, 'about.html')
def nfts_index(request):
  nfts = Nft.objects.all()
  return render(request, 'nfts/index.html', { 'nfts': nfts })
def nfts_detail(request, nft_id):
  nft = Nft.objects.get(id=nft_id)
  selling_form=SellingForm()
  return render(request, 'nfts/detail.html', { 
    'nft': nft,'selling_form': selling_form
     })

class NftCreate(CreateView):
  model = Nft
  fields = '__all__'

class NftUpdate(UpdateView):
  model = Nft
  fields = ['owner']

class NftDelete(DeleteView):
  model=Nft
  success_url='/nfts'

def add_selling(request, nft_id):
  # create a ModelForm instance using the data in request.POST
  form = SellingForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the cat_id assigned
    new_selling = form.save(commit=False)
    new_selling.nft_id = nft_id
    new_selling.save()
  return redirect('detail', nft_id=nft_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the NFT Collector</h1>
<hr />
<p>Buy an NFT from the NFT Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>NFT Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;NFTCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{%url 'about'%}">About</a></li>
          <li><a href="{% url 'nfts_create' %}">Add an NFT</a></li>
          <li><a href="{% url 'index' %}">View All My NFTS</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2022 NFT Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/main_app/nft_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete NFT</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{object.token}} - {{object.creator}}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' nft.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/nft_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
    <h1>Edit <span class="teal-text">{{object.token}} - {{object.creator}}</span></h1>
{% else %}
    <h1>Add an NFT</h1>
{% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/nfts/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>NFT Details</h1>

<div class="card">
  <div class="card-content">
    <span class="card-title">{{ nft.token }}</span>
    <p>Creator: {{ nft.creator }}</p>
    <p>Blockchain: {{ nft.blockchain }}</p>
    <p>Owner: {{ nft.owner }}</p>
  </div>
  <div class="card-action">
    <a href="{% url 'nfts_update' nft.id %}">Edit</a>
    <a href="{% url 'nfts_delete' nft.id %}">Delete</a>
  </div>
</div>
</div>
<div class="col s6">
  <form action="{% url 'add_selling' nft.id %}" method="post">
    {% csrf_token %}
    {{ selling_form.as_p }}
    <input type="submit" class="btn" value="SELL">
  </form>
  <table class="striped">
    <thead>
      <tr><th>Date</th><th>Selling</th></tr>
    </thead>
    <tbody>
      {% for selling in nft.selling_set.all %}
        <tr>
          <td>{{selling.date}}</td>
          <td>{{selling.get_sell_display}}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
</div>
<script>
  var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
  var selectEl = document.getElementById('id_sell');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/nfts/index.html
{% extends 'base.html' %}
{% block content %}

<h1>NFT List</h1>

{% for nft in nfts %}
<a href="{% url 'detail' nft.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ nft.token }}</span>
      <p>Creator: {{ nft.creator }}</p>
      <p>Blockchain: {{ nft.blockchain}}</p>
      <p>Owner: {{ nft.owner }}</p>
    </div>
    </a>
  </div>
{% endfor %}

{% endblock %}